services:
  - type: web
    name: iplytics-backend
    env: java
    rootDir: igit pl-backend
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17